version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: finance_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/finance_app?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    restart: always
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
